name: Run tests on Pull Request

on:
  pull_request:
    branches:
      - main  # or 'master', or whatever your main branch is

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml
          uv pip install -e .

      - name: Run tests
        run: |
          uv pip install pytest
          pytest tests/