name: Run tests on Pull Request

on:
  pull_request:
    branches:
      - main  # or 'master', or whatever your main branch is

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
            echo "DROPBOX_TOKEN=${{ secrets.DROPBOX_TOKEN }}" >> $GITHUB_ENV
            echo "DROPBOX_KEY=${{ secrets.DROPBOX_KEY }}" >> $GITHUB_ENV
            echo "DROPBOX_SECRET=${{ secrets.DROPBOX_SECRET }}" >> $GITHUB_ENV


      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r pyproject.toml
          uv pip install -e .

      - name: Run tests
        run: |
          uv run pytest